# This file was generated by GoReleaser. DO NOT EDIT.
cask "whitespace-tools" do
  name "whitespace-tools"
  desc "CLI tools to fix Git whitespace issues"
  homepage "https://github.com/scottrigby/whitespace-tools"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newline"
  binary "trailingspace"

  on_macos do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_amd64.tar.gz"
      sha256 "00a65fd0d0baad03243a0e78e162dd46095270e2afd69112858ab46f3c6c2799"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_arm64.tar.gz"
      sha256 "ee206862f387cfde2ba23095b87a76f476414e8adf9198270543884671231917"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_amd64.tar.gz"
      sha256 "2bfb8ece252df5f73ae62630402dffc11b4bbb94bfa0c7b58192b9e2f223d934"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_arm64.tar.gz"
      sha256 "43327745ff62b93f8c59a55d302ac0619940f62b1a99c8971be8fe79df14ea06"
    end
  end

  # No zap stanza required
end
