# This file was generated by GoReleaser. DO NOT EDIT.
cask "whitespace-tools" do
  name "whitespace-tools"
  desc "CLI tools to fix Git whitespace issues"
  homepage "https://github.com/scottrigby/whitespace-tools"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newline"
  binary "trailingspace"

  on_macos do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_amd64.tar.gz"
      sha256 "638e226f0a241e832e836198e640092a2c29cbf8aa8554898c1ccecd30f41028"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_arm64.tar.gz"
      sha256 "e5444268118aed8c98a69d81ca5abdfc8684684f607b4709c3cfd76b0f66e53a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_amd64.tar.gz"
      sha256 "726974c1d10608433e853bd90174b5020f76c6ee431bcb6e2b792903213f35cf"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_arm64.tar.gz"
      sha256 "2721b6905b455d38b9fac2807d989ff88de759bd22acc0bebc1c5c8a4c234cac"
    end
  end

  # No zap stanza required
end
