# This file was generated by GoReleaser. DO NOT EDIT.
cask "whitespace-tools" do
  name "whitespace-tools"
  desc "CLI tools to fix Git whitespace issues"
  homepage "https://github.com/scottrigby/whitespace-tools"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newline"
  binary "trailingspace"

  on_macos do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_amd64.tar.gz"
      sha256 "eb4f0b38f12f0b1668669ba8926e5249fc5b0e56d8cbe4165c146433db722577"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_darwin_arm64.tar.gz"
      sha256 "1a3a327b9ecc12fd6605221f743799671d611e77f033d840345cc858e2adbbd6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_amd64.tar.gz"
      sha256 "b283576f7ce419489a4f945595f8d930abfd91b365298cc986e2b76a19f5a224"
    end
    on_arm do
      url "https://github.com/scottrigby/whitespace-tools/releases/download/v#{version}/whitespace-tools_#{version}_linux_arm64.tar.gz"
      sha256 "8dd5624aaa199f7d421542a845a672334218d84235463e804eeb97535756fb63"
    end
  end

  # No zap stanza required
end
